name: btz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

 
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  injectable: ^2.4.1
  equatable: ^2.0.5
  beamer: ^1.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4 
  flutter:
    sdk: flutter
  get_it: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  package_info_plus: ^8.0.2
  flutter_localizations:
    sdk: flutter
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  intl: 0.19.0
  qr_code_scanner_plus: ^2.0.7
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png