name: btz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

 
dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.4
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  flutter_localization: ^0.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  internet_connection_checker: ^0.0.1+3
  easy_mask: ^2.0.1
  camera: ^0.10.5+7
  intl: ^0.19.0
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.3
  validatorless: ^1.2.1
  qr_code_scanner_plus: ^2.0.7
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  collection: ^1.18.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  build_runner: ^2.4.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
